#version: '3.3'
services:

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    volumes:
      - db_value/:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  frontend:
    image: hackathonsagaart/sagaart_frontend:hackathon
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  backend:
    image: hackathonsagaart/sagaart_backend:hackathon
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_value/:/app/static-back/
      - media_value/:/app/media-back/
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build/:/usr/share/nginx/html/
      - static_value:/var/html/static-back/
      - media_value:/var/html/media-back/

    depends_on:
      - backend
      - frontend

volumes:
  db_value:
  static_value:
  media_value: